# Generated by Django 3.0.6 on 2020-06-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated_on',
            new_name='updated_at',
        ),
    ]
