# Generated by Django 3.0.6 on 2020-06-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200604_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
