version: '3'

services:
  db:
    container_name: db-dev
    image: postgres:12.3-alpine

  web:
    container_name: web-dev
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
