version: '3'

services:
  db:
    container_name: db-dev
    image: postgres:12.3-alpine
    env_file:
      - ./.env.dev.db

  web:
    container_name: web-dev
    build:
      context: ./backend
    command: /start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
