# Generated by Django 3.0.6 on 2020-05-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Опросник', 'verbose_name_plural': 'Опросники'},
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=256),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
