# Generated by Django 3.0.7 on 2020-06-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_questionnaire', '0003_auto_20200608_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question/', verbose_name='Изображение'),
        ),
    ]
